// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShrinkFrame.Infrastructure.Persistence;

#nullable disable

namespace ShrinkFrame.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShrinkFrameDbContext))]
    [Migration("20260810162554_AddImmichConnectionTestDetails")]
    partial class AddImmichConnectionTestDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.BatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CapacityAdmissionOverride")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultAudioMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCrf")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultEncoderPreset")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultMaximumResolution")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultSuffix")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt", "Id")
                        .HasDatabaseName("IX_Batches_History");

                    b.ToTable("Batches", (string)null);
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.ImmichConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowInvalidCertificate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Compatibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("EncryptedApiKey")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastTestError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTestKeyId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTestKeyName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTestPermissions")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastTestedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("IsDefault = 1");

                    b.ToTable("ImmichConnections", (string)null);
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.JobAlbumEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("JobId", "Position");

                    b.ToTable("JobAlbums", (string)null);
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.JobAudioCodecEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("JobId", "Position");

                    b.ToTable("JobAudioCodecs", (string)null);
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Crf")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncoderPreset")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaximumResolution")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MetadataCaptureTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataDescription")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MetadataDurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MetadataEffectiveRotation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataFileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MetadataHeight")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MetadataLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("MetadataLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("MetadataMimeType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MetadataSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataVideoCodec")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MetadataWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotBeneficialPublicationOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputArtifactKey")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceArtifactKey")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "CreatedAt", "Id")
                        .HasDatabaseName("IX_Jobs_BatchHistory");

                    b.HasIndex("SourceKind", "SourceConnectionId", "SourceId")
                        .HasDatabaseName("IX_Jobs_SourceDuplicate");

                    b.HasIndex("State", "UpdatedAt", "Id")
                        .HasDatabaseName("IX_Jobs_Queue");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.JobProgressEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BitrateBitsPerSecond")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CompressionPercentage")
                        .HasColumnType("REAL");

                    b.Property<long?>("ElapsedTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EstimatedRemainingTicks")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FramesPerSecond")
                        .HasColumnType("REAL");

                    b.Property<long?>("OutputBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessedTicks")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Speed")
                        .HasColumnType("REAL");

                    b.Property<long?>("TransferBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TransferTotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobId");

                    b.ToTable("JobProgress", (string)null);
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.PublicationAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "StartedAt");

                    b.ToTable("PublicationAttempts", (string)null);
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.ValidationFindingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("ValidationFindings", (string)null);
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.JobAlbumEntity", b =>
                {
                    b.HasOne("ShrinkFrame.Infrastructure.Persistence.JobEntity", "Job")
                        .WithMany("Albums")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.JobAudioCodecEntity", b =>
                {
                    b.HasOne("ShrinkFrame.Infrastructure.Persistence.JobEntity", "Job")
                        .WithMany("AudioCodecs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.JobEntity", b =>
                {
                    b.HasOne("ShrinkFrame.Infrastructure.Persistence.BatchEntity", "Batch")
                        .WithMany("Jobs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.JobProgressEntity", b =>
                {
                    b.HasOne("ShrinkFrame.Infrastructure.Persistence.JobEntity", "Job")
                        .WithOne("Progress")
                        .HasForeignKey("ShrinkFrame.Infrastructure.Persistence.JobProgressEntity", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.PublicationAttemptEntity", b =>
                {
                    b.HasOne("ShrinkFrame.Infrastructure.Persistence.JobEntity", "Job")
                        .WithMany("PublicationAttempts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.ValidationFindingEntity", b =>
                {
                    b.HasOne("ShrinkFrame.Infrastructure.Persistence.JobEntity", "Job")
                        .WithMany("Findings")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.BatchEntity", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("ShrinkFrame.Infrastructure.Persistence.JobEntity", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("AudioCodecs");

                    b.Navigation("Findings");

                    b.Navigation("Progress");

                    b.Navigation("PublicationAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
